### PR TITLE
Nano soi support

### PR DESCRIPTION
**Pull request by idanyok**
1) I changed get_technogoly and get_technology_by_name: changed their layer data parsing to support IMEC (untested) and NanoSOI (tested) layer files. NanoSOI has the layer name in the source field, required special attention or error occurs. IMEC has different notation for group, changed the condition to support it and avoid error.
2) Added support in "path to waveguide" code for zero width components in the XML, in that case, the component will inherit the width from the path

3) ignore the grain.xml update

### CODE REVIEW

**Comment by idanyok** [comment]
Can I get a feedback on this please?

**Comment by lukasc-ubc** [comment]
I have gone through your request and I don’t completely understand it.  Have you used the PDK that is provided by Applied Nanotools?  It is already compatible with SiEPIC-Tools.

**Comment by idanyok** [comment]
I have, and it is not :)
Their layers file doesn't have PINREC, DEVREC etc. which prevents using
"path to waveguide" and snapping features. Also, their layer file naming
convention puts text in the <source> field, which breaks SiEPIC code. (this
also occurs for IMEC PDK for a different reason)
I edited the get_technology functions to account for IMEC and Applied
Nanotools idiosyncrasies to avoid errors
Another problem was that Applied Nanotools PDK adds 2 libraries to KLayout,
and the library your code is looking for to find "waveguide" PCell actually
contains the GDS-based cell - so I changed the code to search through the
libraries with same base name (i.e. NanoSOI), in their case I find also
NanoSOI_PCells and locate the library with the matching PCell
All this I've also done for "Wireguide"

On top of the above, I added a feature (which you may or not like) - if the
waveguide.xml have a 0 width field, the generated waveguide will inherit
the width from the path width. This have not been tested on any CML model.

On their PDK side:

   - Added pin generation code on all their PCells
   - Drawn pins in their GDS-based cells
   - Added "waveguide" & "wireguide" PCell so that your code will find it.
   - Added a Waveguides.xml with proper layers
   - Added the PIN / PINM ... layers in the layer file

Thanks,

Idan Yokev,

Contact phone: +972747237180

Staff Engineer, Electro Optics

*Mellanox Technologies, Ltd.*

**Comment by lukasc-ubc** [comment]
Dear Idan

Thank you for the details. What you describe makes sense. Let me go through this with the applied Nanotools team. 

All the best to you!


Lukas Chrostowski
Professor, Electrical and Computer Engineering
University of British Columbia
Quantum Matter Institute
Member, College of the Royal Society of Canada
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca
https://qmi.ubc.ca/about/directory/lukas-chrostowski

**Comment by lukasc-ubc** [comment]
Idan,

In case you need a working PDK soon, we have done all our tape-outs with ANT using the following PDK: https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK

**Comment by lukasc-ubc** [comment]
@idanyok 
ANT's PDK now supports SiEPIC-Tools.  Can you please let us know if things are working as expected, and if this commit is still required?  
Some of the changes you made are interesting and worth discussing further, e.g., the 0-width path option.
Also curious about the IMEC layers you mention. Does the IMEC PDK support SiEPIC-Tools?

**Pull request closed without merging**
