### PR TITLE
Allow circuit simulation with cells of the same name

### PR DESCRIPTION
**Pull request by stratomaster31**
Remove "$N" from component's name for cell instance arrays of the same name

### CODE REVIEW

**Comment by stratomaster31** [comment]
When two (or more) cells with the same name `CellName` are added to a layout, they are given the following name variants:

* `CellName`
* `CellName$1`

When performin circuit simulation, the ` CellName$1` will not be recognized in the Interconnect Design Kits

This merge removes the extra "$N" characters so that the Interconnect Circuit Simulation will not fail

**Comment by lukasc-ubc** [comment]
@stratomaster31 

thanks for this improvement.  

instead of using a for loop, can you please change your code to use a more efficient approach?

    component1='test name$1'
    component2 = component1.replace('$','').replace(' ', '_')

then 

     text_subckt += ' %s %s %s ' % (component2 + "_" + str(c.idx), nets_str, component2)

**Comment by stratomaster31** [comment]
@lukasc-ubc 

The thing is that we shoud delete the characters from the "$" and not only the "$".

I came up with other workarround. Hope it is now valid

Thanks @lukasc-ubc

**Comment by lukasc-ubc** [comment]
thank you

**Comment by stratomaster31** [comment]
Thank you too

**Pull request merged**
